name: book_library
description: Book library application where u can add and remove a book

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.2
  smooth_star_rating: ^1.0.3
  flutter_speed_dial: ^1.2.1

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  image_test_utils: ^1.0.0
  flutter_launcher_icons: ^0.7.2+1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/book-cover-placeholder-light.png
    - assets/images/book-cover-placeholder-dark.png

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 800
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito/Nunito-ExtraLight.ttf
          weight: 200
